name: github-FORMAT
#test
on:
  pull_request:
    paths-ignore:
      - "**/*.rst"
      - "**/*.md"
      - "doc/**"
    types: [opened, reopened, synchronize]

permissions:
  contents: none

# Cancels any in progress 'workflow' associated with this PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format-check:
    name: format-check
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: OpenCSP
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Black formatting check
        run: |
          pip install black==24.10.0
          cd OpenCSP
          black . -S -C --check --diff --config ./pyproject.toml
