name: github-UBI8-NIGHTLY

# Runs every night at midnight
on:
  workflow_dispatch:
  schedule:
    - cron: '00 00 * * *'

permissions:
  contents: none

# Cancels any in progress 'workflow' associated with this PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubi8-nightly:
    name: ubi8-nightly
    runs-on: [ubuntu-latest]
    permissions:
      packages: read
      contents: read
    container: 
      image: ghcr.io/sandialabs/opencsp:latest-ubi8
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: OpenCSP

      - name: pytest-cov (OpenCSP/example)
        working-directory: OpenCSP/example
        run: |
          python3 -m pip install -r ../requirements.txt
          export PYTHONPATH=$PWD/../
          pytest --color=yes -rs -vv --cov=. --cov-report term --cov-config=.coveragerc

      - name: Pip Upgrade pytest-cov (OpenCSP/example)
        working-directory: OpenCSP/example
        run: |
          python3 -m pip install -U -r ../requirements.txt
          export PYTHONPATH=$PWD/../
          pytest --color=yes -rs -vv --cov=. --cov-report term --cov-config=.coveragerc